db:
  name: envelope_rains
  host: "47.100.196.232"
  port: "3306"
  username: root
  password: "123456"
  charset: utf8

enve:
  total: 10000
  number: 300
  snatch_ratio: 0.8
  per_count: 50
  per_max: 1000
  per_min: 1

redis:
  host: "redis-cn02pak6xbbkuiu9x.redis.volces.com:6379"
  password: "Group12345678"
